apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-serving-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGDCCAgCgAwIBAgIIXqcPXkRxENowDQYJKoZIhvcNAQELBQAwKjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRQwEgYDVQQDEwtldGNkLXNpZ25lcjAeFw0yMTAyMDIxNzQ5
    NDFaFw0zMTAxMzExNzQ5NDFaMCoxEjAQBgNVBAsTCW9wZW5zaGlmdDEUMBIGA1UE
    AxMLZXRjZC1zaWduZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCY
    O0ot8p5ZBgobuSEKMVpVaGczXO0qs+MB9C6FQ+MItcoMGyo9KLiBsjQ5KoW99JZb
    R0xbvVGH+EmDwYdflYF9BNm6Cg+brCHIcJC5qbsUHnAeREfKxIrIszJpYYxgNFW4
    qU0ZydyXj4KW1cs2Qxho4DYqqAPAc2on1U2MT3xG0J1DFjVSK9QxIGkxaljepSVh
    VI3uDq4l9a9TUPsL18VnSXlXPVLfMD54vt4hBz4RYJCMpKnoi4SGhgnN9c78lWIn
    mHEm1lqixmCunNaHsWGdIKIMiVCp9jr+j9nmguXRDG2NcMGVfYr7nruxsD8QMrxU
    w7Rd/4/5TOOap5HTHtehAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMB
    Af8EBTADAQH/MB0GA1UdDgQWBBS1cnNQOQDG5Ps06bQQuwFp140fUDANBgkqhkiG
    9w0BAQsFAAOCAQEAiVD7ErgJ6vkuyCw8TGoMUCJrnBaBzMhmQmhRCcu7sxdifCLL
    Z9J1gv1tLdz0iL7qr7g32tcbPwnD5d8am0ndJRpPYGOjkOGfCzfRJFD9agcQnf7b
    V7AUmNazzc1AlCmxVKwdVmyFW/TFlhx0Zd70bIMP6KfozgNb2eDJEgZxlT0Dt1vN
    XCLPktpyXk24/z4/hJvOhH7BWwpwLm0V0Pt6MUT/dUeSXDuccnJ0YFzDKsHyf/xk
    goajM7eAY9EXQ2oM1Fh1zqmMpp6hqAl2wMrCylttW7UXSUVgo3saD3+/R8/LscXB
    jLbT4pjN380SYPvROGJZZ6Wg7Uc/b7hQzt+kjw==
    -----END CERTIFICATE-----
    
